name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: fedora:32
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: microdnf install cmake ninja-build clang-tools-extra python3-PyYAML

    - name: Configure
      run: cmake -Bbuild -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1

    - name: Build
      run: ninja
      working-directory: build
